### ISSUE TITLE
Unable to read metadata

### ISSUE THREAD

**Issue by vredesbyyrd** [desbma/sacad#30]
Hi, thanks for sharing this great tool. 

`Sacad_r` is returning `Unable to read metadata` on all directories I have tried running it on. 

Example cmd: 

```
Eluvium » sacad_r -d . 1000 cover.jpg                                      
sacad_r: Unable to read metadata for album directory './2003 - Lambent Material'      
sacad_r: Unable to read metadata for album directory './2004 - An Accidental Memory in the Case of Death'
sacad_r: Unable to read metadata for album directory './2005 - Talk Amongst the Trees'     
sacad_r: Unable to read metadata for album directory './2005 - Travels in Constants, Volume 20_ Behind Your Trouble'
sacad_r: Unable to read metadata for album directory './2006 - When I Live by the Garden and the Sea'
sacad_r: Unable to read metadata for album directory './2007 - Copia'                      
sacad_r: Unable to read metadata for album directory './2007 - Indecipherable Text/Disc 01'
sacad_r: Unable to read metadata for album directory './2007 - Indecipherable Text/Disc 02'
sacad_r: Unable to read metadata for album directory './2007 - Jesu _ Eluvium'              
sacad_r: Unable to read metadata for album directory './2014 - Pedals _ Petals'              
sacad_r: Unable to read metadata for album directory './2016 - Unity Engrossed Forever Supposedly'
sacad_r: Unable to read metadata for album directory './2017 - Shuffle Drones'                
sacad_r: Unable to read metadata for album directory './2019 - Pianoworks'                    
Analyzing library: 18dir [00:04,  2.78dir/s, files=160, albums=2, missing covers=1, errors=13]
sacad_r: Unable to find cover for 'Nightmare Ending' by 'Eluvium' from './2013 - Nightmare Ending/Disc 02/08 - Chime.mp3', './2013 - Nightmare Ending/Disc 02/09 - Rain Gently.mp3', './2013 - Nightmare Ending/Disc 02/10 - Impromptu (For the Procession).mp3', './2013 - Nightmare Ending/Disc 02/11 - Covered in Writing.mp3', './2013 - Nightmare Ending/Disc 02/12 - Entendre.mp3', './2013 - Nightmare Ending/Disc 02/13 - Strange Arrivals.mp3', './2013 - Nightmare Ending/Disc 02/14 - Happiness.mp3'
Searching covers: 100%|███████████| 1/1 [00:00<00:00,  2.81cover/s, ok=0, errors=0, no result found=1]
```
I use beets to tag my music, here is the metadata from _lambent material_ first track: 

```
Eluvium » beet info '/mnt/Data/Music/Albums/Eluvium/2003 - Lambent Material/01 - The Unfinished.flac'
/mnt/Data/Music/Albums/Eluvium/2003 - Lambent Material/01 - The Unfinished.flac
             album: Lambent Material
       albumartist: Eluvium
albumartist_credit: Eluvium
     albumdisambig: 
       albumstatus: Official
         albumtype: album
          arranger: 
               art: False
            artist: Eluvium
     artist_credit: Eluvium
              asin: B000093NQ4
          bitdepth: 16
           bitrate: 628101
        catalognum: TRR57
          channels: 2
          comments: 
              comp: False
          composer: 
           country: US
              date: 2003-01-01
              disc: 1
         disctitle: 
         disctotal: 1
            format: FLAC
             genre: Ambient, Electronic, Rock
            genres: Ambient, Electronic, Rock
          grouping: 
             label: Temporary Residence Limited
          language: eng
            length: 278.17333333333335
  mb_albumartistid: 86139012-695b-42f4-98f1-1f353f7230b4
        mb_albumid: 0a37bee7-e8bc-4902-bcd9-b99efd7b5d58
       mb_artistid: 86139012-695b-42f4-98f1-1f353f7230b4
 mb_releasegroupid: 58d3617c-6c24-3197-964f-3debcbc151ff
 mb_releasetrackid: 
        mb_trackid: c7d7e762-b4b6-4221-9989-cc3a31390192
             media: CD
     original_date: 2003-05-06
      original_day: 6
    original_month: 5
     original_year: 2003
   r128_album_gain: 0
   r128_track_gain: 0
        samplerate: 44100
            script: Latn
             title: The Unfinished
             track: 1
        tracktotal: 5
              year: 2003
```
Issue #23 appears to be similar to mine, but I have not been able to resolve it. I run arch linux, with `sacad 2.2.2-1` from the aur. Arch recently updated to python 3.8. Doubt that is the cause but figured it worth mentioning. 

Thanks for your time.
